Fixed missing 'save' button for small videos, loaded for the first time
Mishiranu/Dashchan pull request #280
Opened 2020-12-29 19:59 UTC by ousennin

2020-12-29 22:49 UTC, Mishiranu commented
> Возможно, фикс не очень красивый, зато работает.

В самом деле, не очень красивый, но он вполне корректный.

2020-12-29 22:52 UTC, Mishiranu requested changes

2020-12-29 22:52 UTC, Mishiranu commented on src/com/mishiranu/dashchan/ui/gallery/VideoUnit.java
> +									instance.galleryInstance.callback.invalidateOptionsMenu();
Обрати внимание, что буквально 4 строчками выше есть вызов invalidateOptionsMenu. То есть он будет происходить дважды подряд, и это совершенно ни к чему. Наверное, стоит вынести invalidateOptionsMenu под условие, а второй вызов изнутри условия убрать.

2020-12-30 05:09 UTC, ousennin commented on src/com/mishiranu/dashchan/ui/gallery/VideoUnit.java
> +									instance.galleryInstance.callback.invalidateOptionsMenu();
Сделано.

2020-12-30 11:07 UTC, merged

2020-12-30 12:14 UTC, Mishiranu reviewed
Не знаю, как теперь убрать плашку changes requested, попробую что-то тут написать, лол.

2020-12-30 12:20 UTC, Mishiranu reviewed
test

2020-12-30 12:20 UTC, Mishiranu commented on src/com/mishiranu/dashchan/ui/gallery/VideoUnit.java
> +								instance.galleryInstance.callback.invalidateOptionsMenu();
test

2020-12-30 12:20 UTC, Mishiranu commented
Короче, яннп.